### ISSUE TITLE
[BUG]: Rerunning a single Playwright shard in Github Actions results in a report that gets stuck in In Progress

### ISSUE THREAD

**Issue by angelo-loria** [microsoft/playwright-testing-service#137]
When using the reporting dashboard with sharding in Github Actions, a re-run of a failed shard results in a report that is stuck in In Progress

**To Reproduce**
1. Execute tests in Github Actions with sharding enabled
```
 jobs:
  playwright_test:
    name: Playwright Test 
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5]
        shardTotal: [5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Yarn Install
        run: yarn install

      - name: Run Tests
        run: yarn test:ci --workers=2 --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        env:
          # Access token and regional endpoint for Microsoft Playwright Testing
          PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{ secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN }}
          PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
```

3. Make sure that some shards fail: ![Image](https://github.com/user-attachments/assets/c9279c28-946f-48d6-a3ed-3998997d29b3)
5. The initial run results in a working report dashboard: ![Image](https://github.com/user-attachments/assets/ee02cf96-3138-4b95-80a2-5b9c7928a7a0)
6. Rerun the failed jobs in Actions: ![Image](https://github.com/user-attachments/assets/92848204-3778-4514-abc8-9d63e55d5b3b)
7. After rerunning jobs, we have different results: ![Image](https://github.com/user-attachments/assets/0a82e41b-08ed-4715-b96b-dd984e9303a1)
8. The report gets stuck in In Progress and can't be accessed: ![Image](https://github.com/user-attachments/assets/13e53209-c26c-4a3c-b2c4-fd7419c5f9ad)

**Setup information (please complete the following information):**
 - Azure Subscription Id: af4ec0b8-998c-4cf2-900b-5352b121dbf9
 - Workspace Name: Kaleidoscope
 - Playwright Version: 1.48.1
